---
# handlers file for roles/apache

- name: Redémarrage du service Apache pour prise en compte des modifs de config.
  systemd:
    name: "{{ apache_service_name }}"
    state: restarted
  listen: restart_apache
